services:
    sparkson.data_exporter.factory:
        class: Sparkson\DataExporterBundle\Exporter\ExporterFactory
        arguments:
            - "@sparkson.data_exporter.type_registry"
            - "@sparkson.data_exporter.default_column_resolver"

    sparkson.data_exporter.type_registry:
        class: Sparkson\DataExporterBundle\Exporter\Type\TypeRegistry

    sparkson.data_exporter.default_column_resolver:
        class: Sparkson\DataExporterBundle\Exporter\ValueResolver\DefaultValueResolver

    # Column types

    sparkson.data_exporter.type.string:
        class: Sparkson\DataExporterBundle\Exporter\Core\Type\StringType
        tags:
            -  { name: sparkson.data_exporter.type }

    sparkson.data_exporter.type.number:
        class: Sparkson\DataExporterBundle\Exporter\Core\Type\NumberType
        tags:
            -  { name: sparkson.data_exporter.type }

    sparkson.data_exporter.type.map:
        class: Sparkson\DataExporterBundle\Exporter\Core\Type\MapType
        tags:
            -  { name: sparkson.data_exporter.type }

    sparkson.data_exporter.type.datetime:
        class: Sparkson\DataExporterBundle\Exporter\Core\Type\DateTimeType
        tags:
            -  { name: sparkson.data_exporter.type }

    sparkson.data_exporter.type.callback:
        class: Sparkson\DataExporterBundle\Exporter\Core\Type\CallbackType
        tags:
            -  { name: sparkson.data_exporter.type }

    sparkson.data_exporter.type.boolean:
        class: Sparkson\DataExporterBundle\Exporter\Core\Type\BooleanType
        tags:
            -  { name: sparkson.data_exporter.type }

    sparkson.data_exporter.type.raw:
        class: Sparkson\DataExporterBundle\Exporter\Core\Type\RawType
        tags:
            -  { name: sparkson.data_exporter.type }
